from __future__ import annotations

from typing import TYPE_CHECKING

from archinstall.lib.args import ArchConfig
from archinstall.lib.mirror.mirror_handler import MirrorListHandler
from archinstall.lib.models.application import (
    ApplicationConfiguration,
    Audio,
    AudioConfiguration,
    BluetoothConfiguration,
    PowerManagement,
    PowerManagementConfiguration,
    ZramAlgorithm,
    ZramConfiguration,
)
from archinstall.lib.models.authentication import AuthenticationConfiguration
from archinstall.lib.models.bootloader import Bootloader, BootloaderConfiguration
from archinstall.lib.models.locale import LocaleConfiguration
from archinstall.lib.models.mirrors import (
    CustomRepository,
    MirrorConfiguration,
    SignCheck,
    SignOption,
)
from archinstall.lib.models.network import NetworkConfiguration, NicType
from archinstall.lib.models.packages import Repository
from archinstall.lib.models.profile import ProfileConfiguration
from archinstall.lib.models.users import Password, User
from archinstall.lib.profile.profiles_handler import profile_handler

from .constants import (
    ARCHLINUXCN_URL,
    BASE_PACKAGES,
    BROWSER_OPTIONS,
    COUNTRY_TIMEZONES,
    FONTCONFIG_CJK_ALIASES,
    GPU_PACKAGES,
)
from .detection import calculate_kmscon_font_size, needs_kmscon
from .disk import build_disk_layout
from .mirrors import build_mirror_config

if TYPE_CHECKING:
    from .wizard import WizardState


# =============================================================================
# Config builder
# =============================================================================

def build_default_config(
    country: str | None,
    locale: str,
    mirror_list_handler: MirrorListHandler,
) -> ArchConfig:
    """Build ArchConfig with all opinionated defaults pre-filled."""
    config = ArchConfig()

    # Locale
    config.locale_config = LocaleConfiguration(
        kb_layout='',  # intentionally empty, set via vconsole.conf post-install
        sys_lang=locale,
        sys_enc='UTF-8',
    )

    # Bootloader: EFISTUB + UKI
    config.bootloader_config = BootloaderConfiguration(
        bootloader=Bootloader.Efistub,
        uki=True,
        removable=False,
    )

    # Applications: PipeWire + Bluetooth + tuned
    config.app_config = ApplicationConfiguration(
        audio_config=AudioConfiguration(audio=Audio.PIPEWIRE),
        bluetooth_config=BluetoothConfiguration(enabled=True),
        power_management_config=PowerManagementConfiguration(
            power_management=PowerManagement.TUNED,
        ),
    )

    # Swap: zram with lzo-rle
    config.swap = ZramConfiguration(enabled=True, algorithm=ZramAlgorithm.LZO_RLE)

    # Profile: Minimal
    minimal_profile = profile_handler.get_profile_by_name('Minimal')
    if minimal_profile:
        config.profile_config = ProfileConfiguration(profile=minimal_profile)

    # Network: default to NM+iwd
    config.network_config = NetworkConfiguration(type=NicType.NM_IWD)

    # Timezone (from detected country)
    if country and country in COUNTRY_TIMEZONES:
        config.timezone = COUNTRY_TIMEZONES[country]

    # Mirror configuration (with fallback pools)
    config.mirror_config = build_mirror_config(country, mirror_list_handler)

    # archlinuxcn repository for CN users
    if country == 'CN':
        config.mirror_config.custom_repositories.append(
            CustomRepository(
                name='archlinuxcn',
                url=ARCHLINUXCN_URL,
                sign_check=SignCheck.Optional,
                sign_option=SignOption.TrustAll,
            ),
        )

    # Hostname, kernel, NTP, packages, downloads
    config.hostname = 'archlinux'
    config.kernels = ['linux']
    config.ntp = True
    config.packages = list(BASE_PACKAGES)
    config.parallel_downloads = 0  # 0 = pacman default (5), matches Bash version

    return config


# =============================================================================
# kmscon config generation
# =============================================================================

def generate_kmscon_config(
    font_name: str,
    font_size: int,
    has_gpu: bool,
) -> str:
    """Generate /etc/kmscon/kmscon.conf content based on detected environment.

    Args:
        font_name: Font family name (e.g. 'Noto Sans CJK SC').
        font_size: Calculated font size based on screen resolution.
        has_gpu: Whether a discrete/integrated GPU was detected (enables hwaccel).
    """
    lines = [
        '# Generated by arch-bootstrap',
        '# See kmscon.conf(5) for all available options',
        '',
        '### Graphics Options',
        'drm',
        *(['hwaccel'] if has_gpu else ['no-hwaccel']),
        '',
        '### Font Options',
        'font-engine=pango',
        f'font-name={font_name}',
        f'font-size={font_size}',
        '',
        '### Terminal Options',
        'term=xterm-256color',
        'sb-size=10000',
        '',
    ]
    return '\n'.join(lines)


# =============================================================================
# Fontconfig generation
# =============================================================================

def _fontconfig_match_alias(from_name: str, to_name: str) -> str:
    """Generate a fontconfig <match> block that aliases one font family to another."""
    return (
        '  <match target="pattern">\n'
        '    <test qual="any" name="family">\n'
        f'      <string>{from_name}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="assign" binding="same">\n'
        f'      <string>{to_name}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def _fontconfig_generic_override(generic: str, font_name: str) -> str:
    """Generate a fontconfig <match> that prepends a font to a generic family."""
    return (
        '  <match target="pattern">\n'
        '    <test qual="any" name="family">\n'
        f'      <string>{generic}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="prepend" binding="strong">\n'
        f'      <string>{font_name}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def _fontconfig_lang_override(lang: str, generic: str, font_name: str) -> str:
    """Generate a fontconfig <match> that prepends a font for a specific language."""
    return (
        '  <match>\n'
        '    <test name="lang" compare="contains">\n'
        f'      <string>{lang}</string>\n'
        '    </test>\n'
        '    <test name="family">\n'
        f'      <string>{generic}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="prepend">\n'
        f'      <string>{font_name}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def generate_fontconfig(cjk_font_name: str, locale: str) -> str:
    """Generate ~/.config/fontconfig/fonts.conf for CJK locale users.

    Sets the selected CJK font as the preferred font for the locale's language,
    disables embedded bitmap fonts, and aliases common CJK font names to the
    selected font so applications requesting unavailable fonts degrade gracefully.

    Args:
        cjk_font_name: The CJK font family selected by the user (e.g. 'Noto Sans CJK SC').
        locale: System locale (e.g. 'zh_CN.UTF-8').
    """
    # Determine language code for fontconfig lang matching
    lang = locale.split('_')[0]  # 'zh' or 'ja'

    sections: list[str] = [
        '<?xml version="1.0"?>',
        '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">',
        '<!-- Generated by arch-bootstrap -->',
        '<fontconfig>',
        '',
        '  <!-- Disable embedded bitmap fonts -->',
        '  <match target="font">',
        '    <edit name="embeddedbitmap" mode="assign">',
        '      <bool>false</bool>',
        '    </edit>',
        '  </match>',
        '',
        '  <!-- CJK font defaults for serif/sans-serif/monospace -->',
        _fontconfig_lang_override(lang, 'serif', cjk_font_name),
        _fontconfig_lang_override(lang, 'sans-serif', cjk_font_name),
        _fontconfig_lang_override(lang, 'monospace', cjk_font_name),
    ]

    # Font alias mappings: redirect common CJK font names to the selected font
    aliases = FONTCONFIG_CJK_ALIASES.get(lang, [])
    if aliases:
        sections.append('')
        sections.append(f'  <!-- Alias common {lang.upper()} fonts to {cjk_font_name} -->')
        for alias_name in aliases:
            sections.append(_fontconfig_match_alias(alias_name, cjk_font_name))

    sections.extend([
        '',
        '</fontconfig>',
        '',
    ])

    return '\n'.join(sections)


# =============================================================================
# Wizard state → config application
# =============================================================================

def apply_wizard_state_to_config(
    state: WizardState,
    config: ArchConfig,
    mirror_list_handler: MirrorListHandler,
) -> None:
    """Apply wizard selections to ArchConfig."""
    # Locale
    config.locale_config = LocaleConfiguration(
        kb_layout='',
        sys_lang=state.locale,
        sys_enc='UTF-8',
    )

    # Timezone
    if state.country and state.country in COUNTRY_TIMEZONES:
        config.timezone = COUNTRY_TIMEZONES[state.country]

    # Mirror regions (with fallback pools)
    new_mirror = build_mirror_config(state.country, mirror_list_handler)
    if config.mirror_config is None:
        config.mirror_config = new_mirror
    else:
        config.mirror_config.mirror_regions = new_mirror.mirror_regions
        config.mirror_config.custom_servers = new_mirror.custom_servers

    # archlinuxcn
    # Remove existing archlinuxcn if any
    config.mirror_config.custom_repositories = [
        r for r in config.mirror_config.custom_repositories
        if r.name != 'archlinuxcn'
    ]
    if state.country == 'CN':
        config.mirror_config.custom_repositories.append(
            CustomRepository(
                name='archlinuxcn',
                url=ARCHLINUXCN_URL,
                sign_check=SignCheck.Optional,
                sign_option=SignOption.TrustAll,
            ),
        )

    # Multilib
    if state.multilib:
        if Repository.Multilib not in config.mirror_config.optional_repositories:
            config.mirror_config.optional_repositories.append(Repository.Multilib)
    else:
        config.mirror_config.optional_repositories = [
            r for r in config.mirror_config.optional_repositories
            if r != Repository.Multilib
        ]

    # Disk layout
    if state.disk_device:
        config.disk_config = build_disk_layout(state.disk_device)

    # Network
    config.network_config = NetworkConfiguration(type=state.network_type)

    # GPU packages
    gpu_packages = list(GPU_PACKAGES['common'])  # always include mesa
    for vendor in state.gpu_vendors:
        gpu_packages.extend(GPU_PACKAGES.get(vendor, []))
    # Merge with base packages (avoid duplicates)
    all_packages = list(BASE_PACKAGES)
    for pkg in gpu_packages:
        if pkg not in all_packages:
            all_packages.append(pkg)
    # kmscon for non-English locales
    if needs_kmscon(state.locale) and 'kmscon' not in all_packages:
        all_packages.append('kmscon')
    # kmscon font package
    if state.kmscon_font_package and state.kmscon_font_package not in all_packages:
        all_packages.append(state.kmscon_font_package)
    # Browser packages (pacman only; AUR browsers handled in post-install)
    for browser_key in state.browsers:
        info = BROWSER_OPTIONS.get(browser_key, {})
        if not info.get('aur', False):
            pkg = info.get('package', '')
            if pkg and pkg not in all_packages:
                all_packages.append(pkg)
    config.packages = all_packages

    # Authentication
    users = []
    if state.username and state.user_password:
        users.append(User(
            username=state.username,
            password=state.user_password,
            sudo=True,
        ))
    config.auth_config = AuthenticationConfiguration(
        root_enc_password=state.root_password,
        users=users,
    )

    # Custom commands for kmscon setup
    if needs_kmscon(state.locale):
        config.custom_commands = [
            'systemctl disable getty@tty1',
            'systemctl enable kmsconvt@tty1',
        ]
    else:
        config.custom_commands = []

    # Services (empty — handled by app_config and profile)
    config.services = []
