from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING
from xml.sax.saxutils import escape as xml_escape

from archinstall.lib.args import ArchConfig
from archinstall.lib.mirror.mirror_handler import MirrorListHandler
from archinstall.lib.models.application import (
    ApplicationConfiguration,
    Audio,
    AudioConfiguration,
    BluetoothConfiguration,
    PowerManagement,
    PowerManagementConfiguration,
    ZramAlgorithm,
    ZramConfiguration,
)
from archinstall.lib.models.authentication import AuthenticationConfiguration
from archinstall.lib.models.bootloader import Bootloader, BootloaderConfiguration
from archinstall.lib.models.device import SubvolumeModification
from archinstall.lib.models.locale import LocaleConfiguration
from archinstall.lib.models.mirrors import (
    MirrorConfiguration,
)
from archinstall.lib.models.network import NetworkConfiguration, NicType
from archinstall.lib.models.packages import Repository
from archinstall.lib.models.profile import ProfileConfiguration
from archinstall.lib.models.users import Password, User
from archinstall.lib.profile.profiles_handler import profile_handler

from .constants import (
    AUDIO_FIRMWARE_OPTIONS,
    BASE_FONT_OPTIONS,
    BASE_PACKAGES,
    BROWSER_OPTIONS,
    CLIPBOARD_PACKAGES,
    CLIPBOARD_WAYLAND_PACKAGES,
    COUNTRY_TIMEZONES,
    DEV_ENVIRONMENT_OPTIONS,
    FILE_MANAGER_OPTIONS,
    FONTCONFIG_CJK_ALIASES,
    FONTCONFIG_CJK_MONO,
    GAMING_OPTIONS,
    GPU_PACKAGES,
    INPUT_METHOD_PACKAGES,
    KEYRING_OPTIONS,
    NERD_FONT_OPTIONS,
    POLKIT_AGENT_OPTIONS,
    PROXY_TOOL_OPTIONS,
    REMOTE_DESKTOP_OPTIONS,
    TERMINAL_ENHANCEMENT_PACKAGES,
    VM_OPTIONS,
)
from .detection import calculate_kmscon_font_size, needs_kmscon
from .disk import build_disk_layout
from .mirrors import build_mirror_config

if TYPE_CHECKING:
    from .wizard import WizardState


# =============================================================================
# Config builder
# =============================================================================

def build_default_config(
    country: str | None,
    locale: str,
    mirror_list_handler: MirrorListHandler,
) -> ArchConfig:
    """Build ArchConfig with all opinionated defaults pre-filled."""
    config = ArchConfig()

    # Locale
    config.locale_config = LocaleConfiguration(
        kb_layout='',  # intentionally empty, set via vconsole.conf post-install
        sys_lang=locale,
        sys_enc='UTF-8',
    )

    # Bootloader: EFISTUB + UKI
    config.bootloader_config = BootloaderConfiguration(
        bootloader=Bootloader.Efistub,
        uki=True,
        removable=False,
    )

    # Applications: PipeWire + Bluetooth + tuned
    config.app_config = ApplicationConfiguration(
        audio_config=AudioConfiguration(audio=Audio.PIPEWIRE),
        bluetooth_config=BluetoothConfiguration(enabled=True),
        power_management_config=PowerManagementConfiguration(
            power_management=PowerManagement.TUNED,
        ),
    )

    # Swap: zram with lzo-rle
    config.swap = ZramConfiguration(enabled=True, algorithm=ZramAlgorithm.LZO_RLE)

    # Profile: Minimal
    minimal_profile = profile_handler.get_profile_by_name('Minimal')
    if minimal_profile:
        config.profile_config = ProfileConfiguration(profile=minimal_profile)

    # Network: default to NM+iwd
    config.network_config = NetworkConfiguration(type=NicType.NM_IWD)

    # Timezone (from detected country)
    if country and country in COUNTRY_TIMEZONES:
        config.timezone = COUNTRY_TIMEZONES[country]

    # Mirror configuration (with fallback pools)
    config.mirror_config = build_mirror_config(country, mirror_list_handler)

    # Hostname, kernel, NTP, packages, downloads
    config.hostname = 'archlinux'
    config.kernels = ['linux']
    config.ntp = True
    config.packages = list(BASE_PACKAGES)
    config.parallel_downloads = 0  # 0 = pacman default (5), matches Bash version

    return config


# =============================================================================
# kmscon config generation
# =============================================================================

def generate_kmscon_config(
    font_name: str,
    font_size: int,
    has_gpu: bool,
) -> str:
    """Generate /etc/kmscon/kmscon.conf content based on detected environment.

    Args:
        font_name: Font family name (e.g. 'Noto Sans CJK SC').
        font_size: Calculated font size based on screen resolution.
        has_gpu: Whether a discrete/integrated GPU was detected (enables hwaccel).
    """
    lines = [
        '# Generated by arch-bootstrap',
        '# See kmscon.conf(5) for all available options',
        '',
        '### Graphics Options',
        'drm',
        *(['hwaccel'] if has_gpu else ['no-hwaccel']),
        '',
        '### Font Options',
        'font-engine=pango',
        f'font-name={font_name}',
        f'font-size={font_size}',
        '',
        '### Terminal Options',
        'term=xterm-256color',
        'sb-size=10000',
        '',
    ]
    return '\n'.join(lines)


_KMSCON_GREETD_WARNING = '''\
# Warn about kmscon/greetd DRM conflict when kmscon is on tty1.
# Suppress this message by creating ~/.hushlogin

[ -f "$HOME/.hushlogin" ] && return 0

# Only warn if kmscon is actually enabled on tty1
systemctl is-enabled kmsconvt@tty1.service >/dev/null 2>&1 || return 0

printf '\\n'
printf '  \\033[33mNote:\\033[0m kmscon is running on tty1.\\n'
printf '  If you install a display manager (e.g. greetd), move kmscon first:\\n'
printf '    sudo systemctl disable kmsconvt@tty1\\n'
printf '    sudo systemctl enable getty@tty1\\n'
printf '    sudo systemctl disable getty@tty2\\n'
printf '    sudo systemctl enable kmsconvt@tty2\\n'
printf '  To hide this message: touch ~/.hushlogin\\n'
printf '\\n'
'''


def get_kmscon_greetd_warning() -> str:
    """Return the content of the kmscon/greetd DRM conflict warning script."""
    return _KMSCON_GREETD_WARNING


# =============================================================================
# Fontconfig generation
# =============================================================================

def _fontconfig_match_alias(from_name: str, to_name: str) -> str:
    """Generate a fontconfig <match> block that aliases one font family to another."""
    escaped_from = xml_escape(from_name)
    escaped_to = xml_escape(to_name)
    return (
        '  <match target="pattern">\n'
        '    <test qual="any" name="family">\n'
        f'      <string>{escaped_from}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="assign" binding="same">\n'
        f'      <string>{escaped_to}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def _fontconfig_generic_override(generic: str, font_name: str) -> str:
    """Generate a fontconfig <match> that prepends a font to a generic family."""
    return (
        '  <match target="pattern">\n'
        '    <test qual="any" name="family">\n'
        f'      <string>{generic}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="prepend" binding="strong">\n'
        f'      <string>{font_name}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def _fontconfig_lang_override(lang: str, generic: str, font_name: str) -> str:
    """Generate a fontconfig <match> that prepends a font for a specific language."""
    return (
        '  <match>\n'
        '    <test name="lang" compare="contains">\n'
        f'      <string>{lang}</string>\n'
        '    </test>\n'
        '    <test name="family">\n'
        f'      <string>{generic}</string>\n'
        '    </test>\n'
        '    <edit name="family" mode="prepend">\n'
        f'      <string>{font_name}</string>\n'
        '    </edit>\n'
        '  </match>'
    )


def generate_fontconfig(cjk_font_name: str, locale: str, nerd_font_families: list[str] | None = None) -> str:
    """Generate ~/.config/fontconfig/fonts.conf for CJK locale users.

    Sets the selected CJK font as the preferred font for the locale's language,
    disables embedded bitmap fonts, and aliases common CJK font names to the
    selected font so applications requesting unavailable fonts degrade gracefully.

    Args:
        cjk_font_name: The CJK font family selected by the user (e.g. 'Noto Sans CJK SC').
        locale: System locale (e.g. 'zh_CN.UTF-8').
    """
    # Determine language code for fontconfig lang matching
    lang = locale.split('_')[0]  # 'zh' or 'ja'

    # Derive monospace CJK variant from explicit mapping.
    # Fonts without a mono variant in the same package won't override monospace.
    mono_cjk_font_name = FONTCONFIG_CJK_MONO.get(cjk_font_name)

    sections: list[str] = [
        '<?xml version="1.0"?>',
        '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">',
        '<!-- Generated by arch-bootstrap -->',
        '<fontconfig>',
        '',
        '  <!-- Disable embedded bitmap fonts -->',
        '  <match target="font">',
        '    <edit name="embeddedbitmap" mode="assign">',
        '      <bool>false</bool>',
        '    </edit>',
        '  </match>',
        '',
        '  <!-- CJK font defaults for serif/sans-serif/monospace -->',
        _fontconfig_lang_override(lang, 'serif', cjk_font_name),
        _fontconfig_lang_override(lang, 'sans-serif', cjk_font_name),
    ]

    if nerd_font_families:
        for nf in nerd_font_families:
            sections.append(_fontconfig_generic_override('monospace', nf))
    if mono_cjk_font_name:
        sections.append(_fontconfig_lang_override(lang, 'monospace', mono_cjk_font_name))

    # Font alias mappings: redirect common CJK font names to the selected font
    aliases = FONTCONFIG_CJK_ALIASES.get(lang, [])
    if aliases:
        sections.append('')
        sections.append(f'  <!-- Alias common {lang.upper()} fonts to {cjk_font_name} -->')
        for alias_name in aliases:
            sections.append(_fontconfig_match_alias(alias_name, cjk_font_name))

    sections.extend([
        '',
        '</fontconfig>',
        '',
    ])

    return '\n'.join(sections)


# =============================================================================
# Wizard state → config application
# =============================================================================

def apply_wizard_state_to_config(
    state: WizardState,
    config: ArchConfig,
    mirror_list_handler: MirrorListHandler,
) -> None:
    """Apply wizard selections to ArchConfig."""
    # Locale
    config.locale_config = LocaleConfiguration(
        kb_layout='',
        sys_lang=state.locale,
        sys_enc='UTF-8',
    )

    # Timezone
    if state.country and state.country in COUNTRY_TIMEZONES:
        config.timezone = COUNTRY_TIMEZONES[state.country]

    # Mirror regions (with fallback pools)
    new_mirror = build_mirror_config(state.country, mirror_list_handler)
    if config.mirror_config is None:
        config.mirror_config = new_mirror
    else:
        config.mirror_config.mirror_regions = new_mirror.mirror_regions
        config.mirror_config.custom_servers = new_mirror.custom_servers

    # Multilib
    if state.multilib:
        if Repository.Multilib not in config.mirror_config.optional_repositories:
            config.mirror_config.optional_repositories.append(Repository.Multilib)
    else:
        config.mirror_config.optional_repositories = [
            r for r in config.mirror_config.optional_repositories
            if r != Repository.Multilib
        ]

    # Disk layout
    if state.disk_device:
        config.disk_config = build_disk_layout(state.disk_device)
        # Add @swap subvolume for hibernation (no compression — swap on
        # compressed btrfs is problematic)
        if state.hibernation and config.disk_config:
            for dev_mod in config.disk_config.device_modifications:
                for part in dev_mod.partitions:
                    if part.btrfs_subvols:
                        part.btrfs_subvols.append(
                            SubvolumeModification(Path('@swap'), Path('/swap')),
                        )
                        break

    # Network
    config.network_config = NetworkConfiguration(type=state.network_type)

    # Hostname
    config.hostname = state.hostname

    # GPU packages
    gpu_packages = list(GPU_PACKAGES.get('common', []))  # always include mesa
    for vendor in state.gpu_vendors:
        gpu_packages.extend(GPU_PACKAGES.get(vendor, []))
    # Merge with base packages (avoid duplicates)
    all_packages = list(BASE_PACKAGES)
    for pkg in gpu_packages:
        if pkg not in all_packages:
            all_packages.append(pkg)
    # kmscon for non-English locales
    if needs_kmscon(state.locale) and 'kmscon' not in all_packages:
        all_packages.append('kmscon')
    # kmscon font package
    if state.kmscon_font_package and state.kmscon_font_package not in all_packages:
        all_packages.append(state.kmscon_font_package)
    # Browser packages (pacman only; AUR browsers handled in post-install)
    for browser_key in state.browsers:
        browser_info = BROWSER_OPTIONS.get(browser_key, {})
        if not browser_info.get('aur', False):
            pkg = browser_info.get('package', '')
            if pkg and pkg not in all_packages:
                all_packages.append(pkg)
    # upower for desktop environments that require it
    if state.desktop_env in ('dms', 'dms_manual', 'exo') and 'upower' not in all_packages:
        all_packages.append('upower')
    # btrfs-assistant and gsmartcontrol for non-minimal desktops
    if state.desktop_env != 'minimal':
        if 'btrfs-assistant' not in all_packages:
            all_packages.append('btrfs-assistant')
        if 'gsmartcontrol' not in all_packages:
            all_packages.append('gsmartcontrol')
    # reflector for non-CN users (mirror auto-update)
    if state.country != 'CN' and 'reflector' not in all_packages:
        all_packages.append('reflector')
    # Terminal enhancement
    all_packages.extend(TERMINAL_ENHANCEMENT_PACKAGES)

    # Clipboard support (Wayland extras when a desktop is selected)
    all_packages.extend(CLIPBOARD_PACKAGES)
    if state.desktop_env != 'minimal':
        all_packages.extend(CLIPBOARD_WAYLAND_PACKAGES)
        # Note: CLIPBOARD_WAYLAND_AUR_PACKAGES (comalot-clipsync-git) handled in installation.py

    # Archive extraction
    all_packages.append('unzip')

    # Input method packages
    for im_key in state.input_methods:
        if im_key in INPUT_METHOD_PACKAGES:
            all_packages.extend(INPUT_METHOD_PACKAGES[im_key]['packages'])

    # Font packages
    for font_key in state.base_fonts:
        if font_key in BASE_FONT_OPTIONS:
            all_packages.extend(BASE_FONT_OPTIONS[font_key]['packages'])
    for font_key in state.nerd_fonts:
        if font_key in NERD_FONT_OPTIONS:
            all_packages.extend(NERD_FONT_OPTIONS[font_key]['packages'])

    # Audio firmware packages
    for af_key in state.audio_firmware:
        if af_key in AUDIO_FIRMWARE_OPTIONS:
            all_packages.extend(AUDIO_FIRMWARE_OPTIONS[af_key]['packages'])

    # Polkit agent
    if state.polkit_agent and state.polkit_agent in POLKIT_AGENT_OPTIONS:
        all_packages.extend(POLKIT_AGENT_OPTIONS[state.polkit_agent]['packages'])

    # Keyring
    if state.keyring and state.keyring in KEYRING_OPTIONS:
        all_packages.extend(KEYRING_OPTIONS[state.keyring]['packages'])

    # File managers (non-AUR only; AUR ones handled in installation.py)
    for fm_key in state.file_managers:
        if fm_key in FILE_MANAGER_OPTIONS and not FILE_MANAGER_OPTIONS[fm_key].get('aur', False):
            all_packages.extend(FILE_MANAGER_OPTIONS[fm_key]['packages'])

    # Minimal install: default to yazi as file manager
    if state.desktop_env == 'minimal':
        all_packages.append('yazi')

    # Remote desktop (non-AUR only)
    for rd_key in state.remote_desktop:
        if rd_key in REMOTE_DESKTOP_OPTIONS and not REMOTE_DESKTOP_OPTIONS[rd_key].get('aur', False):
            all_packages.extend(REMOTE_DESKTOP_OPTIONS[rd_key]['packages'])

    # Dev environment packages (non-AUR only)
    for de_key in state.dev_environments:
        if de_key in DEV_ENVIRONMENT_OPTIONS and not DEV_ENVIRONMENT_OPTIONS[de_key].get('aur', False):
            all_packages.extend(DEV_ENVIRONMENT_OPTIONS[de_key]['packages'])

    # Gaming packages (non-AUR only)
    for g_key in state.gaming_tools:
        if g_key in GAMING_OPTIONS and not GAMING_OPTIONS[g_key].get('aur', False):
            all_packages.extend(GAMING_OPTIONS[g_key]['packages'])

    # VM packages (non-AUR only)
    for vm_key in state.vm_options:
        if vm_key in VM_OPTIONS and not VM_OPTIONS[vm_key].get('aur', False):
            all_packages.extend(VM_OPTIONS[vm_key]['packages'])

    # Deduplicate packages while preserving order
    config.packages = list(dict.fromkeys(all_packages))

    # Authentication
    users = []
    if state.username and state.user_password:
        users.append(User(
            username=state.username,
            password=state.user_password,
            sudo=True,
        ))
    config.auth_config = AuthenticationConfiguration(
        root_enc_password=state.root_password,
        users=users,
    )

    # Custom commands for kmscon setup
    if needs_kmscon(state.locale):
        if state.desktop_env in ('dms', 'dms_manual', 'exo'):
            # Graphical DEs use greetd on tty1; put kmscon on tty2 to avoid
            # DRM master contention (kmscon holds /dev/dri/card* open).
            config.custom_commands = [
                'systemctl disable getty@tty2',
                'systemctl enable kmsconvt@tty2',
            ]
        else:
            config.custom_commands = [
                'systemctl disable getty@tty1',
                'systemctl enable kmsconvt@tty1',
            ]
    else:
        config.custom_commands = []

    # Services (empty — handled by app_config and profile)
    config.services = []
